### ISSUE TITLE
Fix migrations issue

### ISSUE THREAD

**Issue by pierrealixt** [kartoza/ford3#113] opened 2019-03-27 06:37 UTC
From Travis:
```
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0024_auto_20190326_0850, 0022_occupation_tasks in ford3).
To fix them run 'python manage.py makemigrations --merge'
```

Should we add in the `migrate` Makefile command, the following command:
`@docker-compose exec uwsgi python manage.py makemigrations --merge`

**Comment by pierrealixt** [comment] 2019-03-27 06:40
The build fails for this PR: https://github.com/kartoza/ford3/pull/112

**Comment by pierrealixt** [comment] 2019-03-27 06:42
Or should we call the `update-migrations` Makefile command?

**Comment by lucernae** [comment] 2019-03-27 06:42
This is caused by different schema that the dev uses when he is developing. So the migration doesn't match with develop.
Simply branch out from develop, then run `makemigrations --merge`. It will fix the migration file. Commit this migration file, make PR to develop, so the new merged migration file is committed.

If we change the models by different person, make sure to do these before merging your PR, so your model schema is up to date. This only needs to be done once per conflict, so we don't have to put it in the Makefile.

**Closed as completed** 2019-03-27 06:53 UTC
