### ISSUE TITLE
TeamCity build is stuck

### ISSUE THREAD

**Issue by pierrealixt** [kartoza/ford3#179] opened 2019-04-03 13:34 UTC
<img width="1416" alt="Screen Shot 2019-04-03 at 15 33 33" src="https://user-images.githubusercontent.com/35932320/55482993-fa9eca80-5625-11e9-845e-0eb909f84893.png">

**Comment by lucernae** [comment] 2019-04-04 10:40
Ok. It seems the host itself is going down

**Comment by lucernae** [comment] 2019-04-05 07:10
Post mortem comment on this issue:

Root cause:
- Disk space is full in the host

Is causing:
- Rancher agent in the host is unresponsive
- Rancher agent is disconnected from Rancher Server
- TeamCity CD process unable to complete it's mission because Rancher Agent never replies. Build is stuck. (Maybe I had to specify a hard timeout on my helper script and fails gracefully).

Solution:
- Find out what causing the disk space is full. Since we only use docker on the host. Docker is the biggest culprit
- Go to `/var/lib/docker` and `du -sh *` to see the size of volumes and containers. Both were ok in this case (since I also installed janitor stack in the environment, so they will clean up). No huge database yet.
- We find out that `/var/lib/docker/overlay2` has big size. This is a merged size, not the actual size. It might look big but not the actual size. But since there're no other culprit, I assume the overlay2 is the cause.
- Just a trivia, if you want to check the disk space used and reported by docker, use `docker system df` add options `--verbose` to see more detail.
- Run docker prune, because we don't know who is the culprit :v. `docker system prune -a`. `-a` option will delete all dangling images/containers/caches/volumes. It's ok because we don't have any data for now. If you have data, it has to be moved to a safe place first.
- Docker prune is very resource intensive. It might take long. But sometimes we want the host to be active ASAP. So, keep an eye until the disk space is cleared somewhat (by using `df -h`). Then restart the host/restart docker. Rancher agent will try to connect again. If rancher agent is connected, rancher server will take the rest (command the service to start up). So you can run docker prune again in the background and let the host finish it's job.

**Closed as completed** 2019-04-05 13:44 UTC
Labels: ci
